apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-db
spec:
  selector:
    matchLabels:
      app: task-db
  template:
    metadata:
      labels:
        app: task-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: task-db
spec:
  ports:
  - port: 5432
  selector:
    app: task-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-app
  template:
    metadata:
      labels:
        app: task-app
    spec:
      containers:
      - name: task-app
        # Replace with your actual ACR name
        image: avesahmed/task-master:latest
        env:
        - name: DB_HOST
          value: task-db
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: task-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: task-app
