apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-app
  template:
    metadata:
      labels:
        app: task-app
    spec:
      containers:
      - name: task-app
        # Replace with your actual ACR name
        image: avesahmed/task-master:latest
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: "task-db"
        - name: DB_NAME
          value: "postgres"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: password
